env:
  es2021: true
  node: true

parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 12
  sourceType: module

plugins:
  - '@typescript-eslint'
  - 'unicorn'
  - 'prettier'
extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/recommended'
  - 'plugin:prettier/recommended'
  - 'plugin:unicorn/recommended'

reportUnusedDisableDirectives: true
rules:
  no-plusplus: 0
  func-names: 0
  no-continue: 0
  no-template-curly-in-string: error
  prefer-destructuring: [error, { object: true, array: false }]
  prefer-template: error
  
  # --- Prettier ---
  prettier/prettier: [error, { singleQuote: true }]

   # --- UNICORN ---
  unicorn/custom-error-definition: error
  unicorn/no-keyword-prefix: error
  unicorn/no-unsafe-regex: error
  unicorn/no-unused-properties: error
  unicorn/import-index: [error, { ignoreImports: true }]
  # Goes against recomended
  unicorn/no-for-loop: off
  unicorn/prefer-node-protocol: off
  